### ISSUE TITLE
Cannot pull data from TABS buoys

### ISSUE THREAD

**Issue by snifflesnrumjum** [kthyng/tabs#2]
Hi @kthyng 
I'm trying to load the TABS data for buoys B and D but it's telling me there's no data available for the time range I've selected. I went ahead and downloaded the full data TXT file and the date range is in the TXT file so I know it exists. I tried getting it direct from the new TABS webpage but it too says the data does not exist.

`import tabs`
`b = tabs.read('B', '8/23/2017', '10/1/2017')`
Returns:
Dataframe was empty. Maybe the requested time series is not available for this time period.

**Comment by kthyng** [comment]
Hi @snifflesnrumjum! This is a problem with the TABS website. I intend to fix it soon, but not immediately. In the meantime, you can access the data by going to the direct address and reading it in. For example:

>import pandas as pd
loc = 'http://pong.tamu.edu/tabswebsite/daily/tabs_B_salt_all'
df = pd.read_table(loc, index_col=0, parse_dates=True)['2017-8-23':'2017-10-1']

If you want velocities, substitute "ven" for "salt" in the file address.

**Comment by snifflesnrumjum** [comment]
Okay thanks! 
This is still way better than copying/pasting two months at a time like I did many years ago!
I'll go ahead and close since it's not really an issue with the code here.
